# Generated by Django 5.1.4 on 2024-12-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_description_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/2024122211:1940<django.db.models.fields.CharField>'),
        ),
    ]
